export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const GET_PROFILES = "GET_PROFILES";
export const SAVE_PROFILES = "SAVE_PROFILES";
export const SET_REACTION = "SET_REACTION";
export const SLICE_PROFILES = "SLICE_PROFILES";
export const GET_MATCHES = "GET_MATCHES";
export const SAVE_MATCHES = "SAVE_MATCHES";
export const UPDATE_PAGENUMBER = "UPDATE_PAGENUMBER";
